// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	ID                 uuid.UUID        `json:"id"`
	UserID             uuid.UUID        `json:"user_id"`
	ExpirationDatetime pgtype.Timestamp `json:"expiration_datetime"`
	Token              string           `json:"token"`
}

type User struct {
	ID              uuid.UUID        `json:"id"`
	Email           string           `json:"email"`
	Username        string           `json:"username"`
	CreatedDatetime pgtype.Timestamp `json:"created_datetime"`
	UpdatedDatetime pgtype.Timestamp `json:"updated_datetime"`
	ProfilePicUrl   pgtype.Text      `json:"profile_pic_url"`
	Admin           bool             `json:"admin"`
	BCryptHash      string           `json:"b_crypt_hash"`
}
